services:
  db:
    build: .
    container_name: postgres16
    environment:
      POSTGRES_USER: phoeniciadigital
      POSTGRES_PASSWORD: pdsoftware
      POSTGRES_DB: pd_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
